name: build-docker-image

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 16 * * *'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: rayyounghong/perforce-helix-core:latest
      - name: Checkout
        uses: actions/checkout@v4
        if: ${{ github.event_name != 'pull_request' }}
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        if: ${{ github.event_name != 'pull_request' }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: rayyounghong/perforce-helix-core
          short-description: ${{ github.event.repository.description }}
